name: manual trigger
on:
  workflow_dispatch:
jobs:
  system_info:
    runs-on: ubuntu-latest
    steps:
      - name: print greetings
        run: echo "welcome to manual trigger"
      - name: print working directory
        run: pwd
      - name: list files
        run: ls -a
      - name: os details
        run: cat /etc/os-release
