name: docker login
on: workflow_dispatch
jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Login
        # You may pin to the exact commit or the version.
        # uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772
        uses: docker/login-action@v3.4.0
        with:
          # Username used to log against the Docker registry
          username: ${{secrets.DOCKER_USERNAME}}
          # Password or personal access token used to log against the Docker registry
          password: ${{secrets.DOCKER_PASSWORD}}
