name: env and secrets
on: workflow_dispatch
jobs:
  environment:
    runs-on: ubuntu-latest
    env:
      NAME: murali krishna
      DB_PASSWORD: Admin@12345
      PORT: 5432
      USERNAME: Adminuser
    steps:
      - name: print greetings
        run: echo "welcome $NAME to github actions class"
      - name: Connecting Database
        run: echo "Connect database using $USERNAME and password $DB_PASSWORD on this Port $PORT"
      - name: connect PostgreSql
        run: echo "postgresql://$USERNAME:$DB_PASSWORD@localhost:$PORT"
  secrets:
    runs-on: ubuntu-latest
    steps:
      - name: print greetings
        run: echo "welcome $NAME to github actions class"

