name: env and secrets
on: workflow_dispatch
jobs:
  environment:
    runs-on: ubuntu-latest
    env:
      NAME: murali krishna
    steps:
      - name: print greetings
        run: echo "welcome $NAME to github actions class"
