name: multi job
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build started
        run: echo "build job is started"
      - name: Checkout
        uses: actions/checkout@v4.2.2 
      - name: list files
        run: ls -a
      - name: view file
        run: cat index.html
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deployment started
        run: echo "deployment started and completed"
  status:
    runs-on: ubuntu-latest
    steps:
      - name: workflow status
        run: echo "build and deployment done"
    
